# Importing numpy

In [2]:
import numpy as np

# The numpy array

In [3]:
a = np.array([1,2,3])

In [4]:
a = np.array([[1,2,3],
              [4,5,6]])

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a = np.array([[[1, 2, 3], 
               [4, 5, 6]], 
                     
              [[7,  8,   9], 
               [10, 11, 12]]])

In [7]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## Indexing

In [8]:
a[0][1][2]

6

In [9]:
a[0][1][2] = -99

In [10]:
a

array([[[  1,   2,   3],
        [  4,   5, -99]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

## Slicing

array[start1:stop1:step1, start2:stop2:step2, ...]

In [11]:
b = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20],[21,22,23,24,25,26,27,28,29,30]])

In [12]:
b[:2,3:7]

array([[ 4,  5,  6,  7],
       [14, 15, 16, 17]])

In [13]:
b[::,:-2:2]

array([[ 1,  3,  5,  7],
       [11, 13, 15, 17],
       [21, 23, 25, 27]])

### Numpy array attributes

* ndim: Returns the number of dimensions (axes) of the array.
* shape: Returns a tuple of integers representing the size of the array in each dimension.
* size: Returns the total number of elements in the array.
* dtype: Returns the data type of the elements in the array (e.g., int32, float64, bool).
* T: Returns the transposed array

In [14]:
a.ndim

3

In [15]:
a.shape

(2, 2, 3)

In [16]:
a.T

array([[[  1,   7],
        [  4,  10]],

       [[  2,   8],
        [  5,  11]],

       [[  3,   9],
        [-99,  12]]])

### Constructors

* np.array(): Creates an array from any iterable object, such as lists, tuples, or other arrays.
* np.zeros(): Creates an array filled with zeros.
* np.ones(): Creates an array filled with ones.
* np.full(): Creates an array filled with a specific value.
* np.arange(): Creates an array with evenly spaced values within a specified interval.
* np.linspace(): Creates an array with a specified number of evenly spaced values between a start and stop value (inclusive).
* np.meshgrid(): Creates an array from coordinates vector
* np.eye(): Creates an identity matrix.
* np.diag(): Creates a diagonal matrix.
* np.empty(): Creates an empty array.

In [17]:
np.zeros((4,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [18]:
np.empty((5,5))

array([[4.67296746e-307, 1.69121096e-306, 9.34609111e-307,
        1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307],
       [1.86921143e-306, 6.23061763e-307, 8.90104239e-307,
        6.89804132e-307, 9.34605716e-307],
       [1.37962456e-306, 1.42418172e-306, 8.06610070e-308,
        6.89810244e-307, 1.22387550e-307],
       [2.22522596e-306, 8.34423917e-308, 9.79107193e-307,
        3.33509775e-317, 2.10081501e-312]])

In [19]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [20]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.meshgrid([1,2,3], [4,5,6])

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]])]

# Broadcasting

In [23]:
l1 = [1,2,3,4,5]

In [24]:
l2 = [6,7,8,9,10]

In [25]:
l1 + l2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [26]:
fl = []
for i,j in zip(l1,l2):
    fl.append(i+j)

In [27]:
fl

[7, 9, 11, 13, 15]

In [28]:
fl = [i+j for i,j in zip(l1,l2)]

In [29]:
a1, a2 = np.array(l1), np.array(l2)

In [30]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [31]:
l1 * 3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [32]:
a1 * 3

array([ 3,  6,  9, 12, 15])

In [33]:
a1 > 2

array([False, False,  True,  True,  True])

In [34]:
a2 == 10

array([False, False, False, False,  True])

<div>
<img src="broadcasting.png" width="600"/>
</div>

* Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (LEFT) side.
* Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
* Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

## Example 1

In [ ]:
a = np.ones((2, 3))
b = np.ones(3)

In [ ]:
print(a.shape)
print(b.shape) 

by rule 1 we pad it with 1

(2,3) \
(1,3) 

by rule 2 we stretch the shape equal 1

(2,3) \
(2,3) 

The shapes match, and we see that the final shape will be (2, 3)

In [ ]:
a + b

## Example 2

In [ ]:
a = np.ones((3, 1))
b = np.ones(3)

In [ ]:
print(a.shape)
print(b.shape) 

by rule 1 we pad it with 1

(3,1) \
(1,3) 

by rule 2 we stretch the shape equal 1

(3,3) \
(3,3) 

The shapes match, and we see that the final shape will be (3, 3)

In [ ]:
a + b

## Example 3

In [ ]:
a = np.ones((3, 2))
b = np.ones(3)

In [ ]:
print(a.shape)
print(b.shape) 

by rule 1 we pad it with 1

(3,2) \
(1,3) 

by rule 2 we stretch the shape equal 1

(3,2) \
(3,3)

The shapes does not match, a error will be raise

In [ ]:
a + b

## Functions

In [ ]:
def my_func(a):

    return a**3+a**2-5*a

In [ ]:
my_func(10)

In [ ]:
my_func(np.array([[1,2,3,4,5],[6,7,8,9,10]]))

# Filtering with boolean

The boolean array must have the same shape as the filtered array.

In [ ]:
a = np.arange(5)

In [ ]:
f = np.array([False, False, False, True, True])

In [ ]:
a[f]

In [ ]:
a = np.array([[1,2], [3,4]])

In [ ]:
f = np.array([[True, False], [False, True]])

In [ ]:
a[f]

In [ ]:
a = np.array([1,2,3,4])
f = np.array([True, True, False, False])

In [ ]:
a[f] = np.array([-99, -99])

In [ ]:
a

In [35]:
a[a>2]

array([ 3,  4,  5,  7,  8,  9, 10, 11, 12])

# Ordering

The boolean array must have the same shape as the filtered array.

In [ ]:
a = np.array([4,1,3,2])

In [ ]:
o = np.array([1, 3, 2, 0])

In [ ]:
a[o]

# Filtering with indexes

The integers array do not need to have the same shape as the filtered array.

In [ ]:
a = np.array([4,1,3,2])

In [ ]:
a[np.array([0,3])]

# Contants

| Synthax | Constant           |
|----------|----------------|
| np.pi        | π = 3.141592…       |
| np.e        | e = 2.718281…    |
| np.inf        | A floating-point positive infinity.  |
| np.nan        | A floating-point “not a number” (NaN) value.       |

In [ ]:
np.nan

In [ ]:
np.pi

# Functions

Many functions are also methods!

## Array manipulation

* reshape(): Gives a new shape to an array without changing its data.
* ravel(): Return a contiguous flattened array.
* flatten(): Return a copy of the array collapsed into one dimension.
* transpose(): Returns an array with axes transposed.
* concatenate(): Join a sequence of arrays along an existing axis.
* stack(): Join a sequence of arrays along a new axis.
* vstack(): Stack arrays in sequence vertically (row wise).
* hstack(): Stack arrays in sequence horizontally (column wise).
* dstack(): Stack arrays in sequence depth wise (along third axis).
* delete(): Return a new array with sub-arrays along an axis deleted.
* insert(): Insert values along the given axis before the given indices.
* append(): Append values to the end of an array.
* flip(): Reverse the order of elements in an array along the given axis.
* unique(): Find the unique elements of an array..

In [ ]:
np.arange(100).reshape(10,10)

In [ ]:
np.concatenate((np.arange(100).reshape(10,10), np.zeros((10,1))), axis=1)

In [ ]:
np.unique(np.array(['LIM', 'LIM', 'SAP', 'SAP', 'BRK']))

<div>
<img src="axis.png" width="600"/>
</div>

## Math

* sin(): sine, element-wise.
* cos(): cosine, element-wise.
* tan(): tangent element-wise.
* arcsin(): inverse sine, element-wise.
* The trigonometric functions goes on...
* round(): Evenly round to the given number of decimals.
* around(): Round elements of the array to the nearest integer.
* floor(): Return the floor.
* ceil(): Return the ceil.
* prod(): Return the product of array elements over a given axis.
* sum(): Return the sum of array elements over a given axis.
* nanprod(): Return the product of array NaNs are treated as one.
* nansum():  Return the sum of array NaNs are treated as one.
* cumprod(): Return the cumulative product of elements over a given axis.
* cumsum(): Return the cumulative sum of elements over a given axis.
* nancumprod(): Return the cumulative product of array elements over a given axis treating Not a Numbers (NaNs) as one.
* nancumsum():Return the cumulative sum of array elements over a given axis treating Not a Numbers (NaNs) as zero.
* exp(): Calculate the exponential of all elements in the input array.
* log(): Natural logarithm, element-wise.
* log2(): Base-2 logarithm of x.
* log10(): Return the base 10 logarithm of the input array, element-wise.
* maximum(): Element-wise maximum of array elements.
* max(): Return the maximum of an array or maximum along an axis.
* amax(): Return the maximum of an array or maximum along an axis.
* minimum(): Element-wise minimum of array elements.
* min(): Return the minimum of an array or minimum along an axis.
* amin(): Return the minimum of an array or minimum along an axis.

In [ ]:
a = np.arange(3*5).reshape(3,5)

In [ ]:
np.sum(a, axis=0)

In [ ]:
np.sum(a, axis=1)

## Sorting, searching, and counting

* sort(): Return a sorted copy of an array.
* lexsort(): Perform an indirect stable sort using a sequence of keys.
* argsort(): Returns the indices that would sort an array.
* argmax(): Returns the indices of the maximum values along an axis.
* nanargmax(): Return the indices of the maximum values in the specified axis ignoring NaNs.
* argmin(): Returns the indices of the minimum values along an axis.
* nanargmin(): Return the indices of the minimum values in the specified axis ignoring NaNs.
* argwhere(): Find the indices of array elements that are non-zero, grouped by element.
* where():Return elements chosen from x or y depending on condition.

In [ ]:
a = np.array([1,2,6,5,4,9,7,8])

In [ ]:
np.argmax(a)

In [ ]:
np.where(a>5, -99, a)

In [ ]:
np.argsort(a)

## Statistics

* percentile(): Compute the q-th percentile of the data along the specified axis.
* nanpercentile(): Compute the qth percentile of the data along the specified axis, while ignoring nan values.
* quantile(): Compute the q-th quantile of the data along the specified axis.
* nanquantile(): Compute the qth quantile of the data along the specified axis, while ignoring nan values.
* median(): Compute the median along the specified axis.
* average(): Compute the weighted average along the specified axis.
* mean(): Compute the arithmetic mean along the specified axis.
* std(): Compute the standard deviation along the specified axis.
* var(): Compute the variance along the specified axis.
* nanmedian(): Compute the median along the specified axis, while ignoring NaNs.
* nanmean(): Compute the arithmetic mean along the specified axis, ignoring NaNs.
* nanstd(): Compute the standard deviation along the specified axis, while ignoring NaNs.
* nanvar(): Compute the variance along the specified axis, while ignoring NaNs.
* corrcoef(): Return Pearson product-moment correlation coefficients.
* cov(): Estimate a covariance matrix, given data and weights.
* histogram(): Compute the histogram of a dataset.

In [ ]:
a = np.arange(100).reshape(10,10)

In [ ]:
np.mean(a, axis=1)

In [ ]:
np.mean(a)

# Numyp modules

## Random

### Random data

* random.randint(): Return random integers from low (inclusive) to high (exclusive)
* random.random(): Return random floats in the half-open interval [0.0, 1.0)
* random.choice(): Generates a random sample from a given array

In [ ]:
a = np.random.randint(0,20,100)

In [ ]:
a

In [ ]:
np.random.choice(a, 10)

### Permutations

* random.shuffle(): Modify an array or sequence in-place by shuffling its contents.
* random.permutation(): Randomly permute a sequence, or return a permuted range.
* random.permuted(): Randomly permute x along axis axis.

In [ ]:
a = np.arange(10)

In [ ]:
a

In [ ]:
np.random.shuffle(a)

In [ ]:
a

### Distributions

* random.lognormal(): Draw samples from a log-normal distribution
* random.normal(): Draw samples from a normal distribution

In [ ]:
a = np.random.normal(loc=0,scale=1,size=20)

In [ ]:
a

## Linalg

### The @ operator

<div>
<img src="matmul.jpg" width="600"/>
</div>

In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([
    [10,11],
    [20,21],
    [30,31]
])

In [ ]:
a @ b

* linalg.dot(): Dot product of two arrays
* linalg.matmul() / @: Matrix product of two arrays
* linalg.outer(): Compute the outer product of two vectors

### Eigenvalues

* linalg.eigvals(): Compute the eigenvalues of a general matrix

### Solving equations and inverting matrices

* linalg.solve(): Solve a linear matrix equation, or system of linear scalar equations
* linalg.inv(): Compute the (multiplicative) inverse of a matrix

$$
\begin{bmatrix}
5 & -3 & 2\\
-7 & 4 & -1\\
-4 & -6 & 0
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
x 
\end{bmatrix}
=
\begin{bmatrix}
4 \\
-2 \\
5 
\end{bmatrix}
$$

In [ ]:
a = np.array([
    [5,-3,2],
    [-7,4,-1],
    [-4,-6,0]
])
b = np.array(
    [4,-2,5]
)

In [ ]:
np.linalg.solve(a,b)