## **Introduction to Python Programming!**


# Course content:

1.   Python basics: sintax, properties, indetation and data types
2.   Operations in Python
3.   Data structures: lists, tuples and dictionaries
4.   Flow control: if...else, while loops, for loops and list comprehension
5.   Python functions: returning data as a result
6.   Lambda functions: small anonymous function












Execute python **syntax** in the command line:

In [ ]:
print("Machine Learning Course")

Machine Learning Course


**Comments** in one line and more than one

In [ ]:
#this is a comment
print("Hello world!")

Hello world!


In [ ]:
"""
This is a comment
written in
more than just one line
"""
print('Go ahead: python basics!')

Go ahead: python basics!


Python **Indentation**: python uses indentation to run different blocks of code/command lines

Refers to the **spaces at the beginning of a code line**!

In [ ]:
if 2 > 1:
  print('Python indetation')

Python indetation


**Creating variables**: a variable is created at the moment you assign a value to it using just one equal!



In [ ]:
x = 10

y = "Pedro"

print(x)

print(y)

10
Pedro


You can also assingn **many values** to **multiple variables** and **output** these multiple values:

In [ ]:
x, y, z = 10, 5.2, 'Pedro'

print(x, y, z)

10 5.2 Pedro


**Data Types**:

Numeric values: integers (int), floating numbers (float)

Boolean values: True or False (bool)

Text values: strings (str)


In [ ]:
x = 10
y = 5.2
z = 'string'

print(type(x), type(y), type(z))

<class 'int'> <class 'float'> <class 'str'>


In [ ]:
x = int(10)
y = float(5.2)
z = str(3)

print(type(x), type(y), type(z))

<class 'int'> <class 'float'> <class 'str'>


In [ ]:
booleano = True


10


In [ ]:
2 == 2

True

In [ ]:
2 != 3

True

In [ ]:
2 != 3 and 2 > 3

False

# **Practice 1**

### *Syntax and Variables:* 
1) Write a program that prints a sentence or word written by you;

<details>
    <summary><p>&#128161;</p></summary>
  
    word = ...
  
    print(...)
  
</details>

2) Create three variables (one with an integer number, another floating number and the last one with a string) and print the values;

<details>
    <summary><p>&#128161;</p></summary>
  
  
    v1 = ...

    v2 = ...

    v3 = ...
  
    print...
</details>

3) Confirm if the variable types created in the previous exercise are correct.




<details>
    <summary><p>&#128161;</p></summary>
  
  
    v1... "int"

    v2... "float"

    v3... "str"

    "type"
</details>

#1)

#2)

#3)

**Basic operations**: python can simple perform operations on variables and values



In [ ]:
2 + 2

4

In [ ]:
2.0 + 2

4.0

In [ ]:
2 * 5

10

In [ ]:
2 * (10 + 2)

24

In [ ]:
8/2

2.0

In [ ]:
8//2

4

In [ ]:
19 % 3

1

In [ ]:
100 ** 2

10000

In [ ]:
width = 10
length = 20
height = 15

In [ ]:
cube_volume = width*length*height

print(cube_volume)

3000


# **Pratice 2**
**Basic operations:** 

1) Write a program that **adds** two numbers.

<details>
    <summary><p>&#128161;</p></summary>
  
  
    v1 =...

    v2 =...

    print v1+v2
  
</details>

2) Write a program that **subtracts** two numbers:

<details>
    <summary><p>&#128161;</p></summary>
  
  
    v1 =...

    v2 =...

    print v1 -v2
  
</details>

3) Write a program that **multiplies** two numbers:

<details>
    <summary><p>&#128161;</p></summary>
  
    v1 =...

    v2 =...

    print v1*v2
  
</details>

4) Write a program that **divides** two numbers

<details>
    <summary><p>&#128161;</p></summary>
 
  
    v1 =...

    v2 =...

    print v1/v2
  
</details>

5) Write a program that uses **parentheses** to ensure the correct order of operations

<details>
    <summary><p>&#128161;</p></summary>
    
    v1 = 10
    v2 = 5
    v3 = 2
    v4 = v1+v2 * v3
    print(v4)

</details>

#1)

#2)

#3)

#4)

**String Manipulation**

In [ ]:
'machine learning'

'machine learning'

In [ ]:
'machine' + 'learning'

'machinelearning'

In [ ]:
'machine' + ' ' + 'learning'

'machine learning'

In [ ]:
ml = 'machine learning'

ml[0]

'm'

In [ ]:
ml[-1]

'g'

In [ ]:
ml[0:7]

'machine'

In [ ]:
ml[:-9]

'machine'

In [ ]:
string = 'learning'

print(f'machine {string}')

machine learning


In [ ]:
print('machine {}'.format(string))

machine learning


In [ ]:
string.upper()

'LEARNING'

In [ ]:
string.lower()

'learning'

# **Practice 3**
**Strings manipulation:** 

1) Write a program that prints your name and a welcome message.

<details>
    <summary><p>&#128161;</p></summary>
  
    name =...

    print hello... welcome...

</details>

3) Write a program that prints the length of a string.

<details>
    <summary><p>&#128161;</p></summary>
 
  
    string =...

    len(...)
  
</details>

4) Write a program that prints the first character of a given string.

<details>
    <summary><p>&#128161;</p></summary>
  
  
    string = ...

    print(string[...])
  
</details>

5) Write a program that converts a given string to uppercase.

<details>
    <summary><p>&#128161;</p></summary>
  
    string = ...

    ...upper()

  
</details>

6) Write a program that converts a given string to lowercase.

<details>
    <summary><p>&#128161;</p></summary>
  
  
    string = ...

    ...lower()
  
</details>

**Data structures:**

List: store multiple items in a single variable **Ordered, changeable and allow duplicate values!**

Tuple: store multiple items in a single variable. **Ordered and unchangeable and allow duplicate values!**

Dictionary: store **data values in keys**, it means, **value pairs**! As of Python version 3.7, dictionaries are **oredered**. Also are changeable but no allow duplicate values!

In [ ]:
numbers_list = [1,2,3,4,5]

str_list = ['hello', 'world']

items_list = ['machine', 4, 'learning', 10, True]

lists_list = [[1,2,3], [6,8,10]]

In [ ]:
numbers_list[0]

1

In [ ]:
lists_list[0][0]

1

In [ ]:
4 in numbers_list

True

In [ ]:
10 not in numbers_list

True

In [ ]:
numbers_list.pop(3)

numbers_list


[1, 2, 3, 5]

In [ ]:
numbers_list.append(4)

numbers_list

[1, 2, 3, 5, 4]

In [ ]:
numbers_list.sort()

numbers_list

[1, 2, 3, 4, 5]

In [ ]:
t = (1, 2, 4, 5)

In [ ]:
t[0]

1

In [ ]:
2 in t

True

In [ ]:
len(t)

4

In [ ]:
geology = {
    'rocktype': 'itabirito',
    'color': 'grey',
    'fe_gl':58,
    'sio2':10
        }

In [ ]:
geology['rocktype']

'itabirito'

In [ ]:
geology['fe_gl']

58

In [ ]:
geology['min_esteril'] = 'minerio'

In [ ]:
geology

{'rocktype': 'itabirito',
 'color': 'grey',
 'fe_gl': 58,
 'sio2': 10,
 'min_esteril': 'minerio'}

In [ ]:
geology.keys()

dict_keys(['rocktype', 'color', 'fe_gl', 'sio2', 'min_esteril'])

In [ ]:
geology.values()

dict_values(['itabirito', 'grey', 58, 10, 'minerio'])

In [ ]:
geology.items()

dict_items([('rocktype', 'itabirito'), ('color', 'grey'), ('fe_gl', 58), ('sio2', 10), ('min_esteril', 'minerio')])

# **Practice 4**
**Data structure:** 

1) Create a list with **5 numbers** and print them:

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    list = [...]

    print()
  
</details>

2) Create a **tuple** of strings and print them:

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    tuple = ()
    
    print...
    
</details>

3) Create a **set** of numbers and print them:

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    num_set = { }


    print(...)

  
</details>

4) Create a **dictionary** with keys and values and print them:

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    dict = {"key1": 3, "key2": 6...}

    print...
  
</details>

5) Add an element to a list:

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    list = [...]

    list.ap...(..)

    print(list)
  
</details>

5) Remove an element from a list:

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    list = [...]

    list.pop...(..)

    print(list)
  
</details>

6) Sort list elements in ascending order:

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    list = [10, 8, 20, 32, 11, 29]

    list.sort()

    print(...)
  
</details>

#1)

#2)

#3)

#4)

#5)

#6)

**Flow control in python:**

If...Else: execute a set of commands if given a logical condition (mathematics conditions, booleans)

While: execute a set of commands as long as a condition is true.

For: iterate over a sequence or a data strucuture (list, tuple, dictionary, ...)



In [ ]:
booleano = True

if booleano:
  print("Se a condição a verdadeira o comando será executado!")

Se a condição a verdadeira o comando será executado!


In [ ]:
x = 10

if x > 0:
    print('número positivo')
else:
    print('número negativo')

número positivo


In [ ]:
a = 1

while a < 5:
  print('Executando..')
  a += 1

Executando..
Executando..
Executando..
Executando..


In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a = 1
for i in range(6):
    a = a + 1
    print(a)

2
3
4
5
6
7


In [ ]:
counter = 0
while counter < 5:
    print('Executando...')
    counter = counter + 1
    print(counter)
print('Fim!')

Executando...
1
Executando...
2
Executando...
3
Executando...
4
Executando...
5
Fim!


In [ ]:
for i in numbers_list:
  print(i)

1
2
3
4
5


In [ ]:
dicionario = {
    'chave1':1,
    'chave2':2,
}

In [ ]:
for k in dicionario:
    print(k)

chave1
chave2


In [ ]:
for i in (1, 10, 20, 45, 67, 76, 78, 90):
    if i % 5 == 0:
        print(i)

10
20
45
90


In [ ]:
l = []
for i in range(5):
    l.append(i)
print(l)

[0, 1, 2, 3, 4]


In [ ]:
l = [i for i in range(5)]

print(l)

[0, 1, 2, 3, 4]


# **Practice 5**
**If, else, While and For:** 

1) Check if a given number is positive or negative:
<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    num =...
    if num > ...:
    print("The number is positive.")
    elif num < ...:
    print("The number is negative.")
    else:
    print("The number is zero.")
  
</details>

2) Print any phrase 10 times using a while loop:

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    i = ...
    while i <= ...:
    print(...)
    i += 1
                 
</details>

3) Print the numbers from 1 to 10 using a while loop:

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    i = 1
    while i < 10:
    print(...)
    i += 1
  
</details>   

4) Print the numbers from 1 to 10 using a for loop:

<details>
    <summary><p>&#128161;</p></summary>
  
    for i in range(...):
    print(i)

</details>

    


#1)

#2)

#3)

#4)

**Python functions:**

**A function is a block of code which only runs when it is called**. You can pass data, known as parameters, into a function. A function can return data as a result.

**Def**: To call a function, use the function name and call parameters on parenthesis (arguments). Information can be passed into functions as arguments, inside the parentheses.

**Lambda**: A lambda function can take any number of arguments, but can only have one expression. The expression is executed and the result is returned.



In [ ]:
def soma(a, b):
    return a + b

In [ ]:
soma(1,2)

3

In [ ]:
def volume(x, y, z):
    return x*y*z

In [ ]:
volume(2,2,2)

8

In [ ]:
soma = lambda a, b : a + b
print(soma(2,4))

6


In [ ]:
volume = lambda x, y, z : x*y*z
print(volume(2,2,2))

8


# **Practice 6**
### Functions:

**Def**

1) Write a function that takes two arguments and returns their sum;

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    def add_numbers(...):
    return ...
  
</details>

2) Write a function that calculates the volume of a cube;
<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    def cube_volume(x):
    volume = x .. 3
    return volume
  
</details>

**Lambda**

3) Write a lambda function that returns the square of a number

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    square = lambda x: ...
    result = square(...)
    print(result)
  
</details>

4) Write a lambda function that returns the product of two numbers

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    product = lambda x, y: ...
    result = product(..., ...)
    print(result)
  
</details>

#1)

#2)

#3)

#4)

**Modules**

In [ ]:
import datetime

In [ ]:
today = datetime.date.today()

today

datetime.date(2023, 2, 7)

In [ ]:
my_birthday = datetime.date(today.year, 7, 11)

In [ ]:
time_to_birthday = my_birthday - today

time_to_birthday

datetime.timedelta(days=154)

In [ ]:
import math

In [ ]:
math.pi

3.141592653589793

In [ ]:
math.nan

nan

In [ ]:
math.exp(10)

22026.465794806718

In [ ]:
math.log(10)

2.302585092994046

In [2]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
b = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
a.size

10

In [ ]:
b.size

10

In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
a.shape


(9,)

In [ ]:
b.shape

(2, 5)

In [ ]:
a[0]

array([1, 2, 3, 4, 5])

In [ ]:
a[0][2]

3

In [ ]:
b[0:3]

array([1, 2, 3])

In [ ]:
a[1:,:]

array([[ 6,  7,  8,  9, 10]])

In [ ]:
c = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
r = c.reshape(5,2)

r

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
print(c.mean())

print(c.std())

print(c.sum())

print(c.cumsum())

5.5
2.8722813232690143
55
[ 1  3  6 10 15 21 28 36 45 55]


In [ ]:
np.where(c>4)

(array([4, 5, 6, 7, 8, 9], dtype=int64),)

In [ ]:
np.where(c>4, 0, 1)

array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0])

In [ ]:
a = np.array([1,1,1,2,2,2])

In [ ]:
np.unique(a)

array([1, 2])

In [ ]:
b = np.array([2,1,6,7,5])

In [ ]:
np.sort(b)

array([1, 2, 5, 6, 7])

numpy.argmin() and numpy.argmax() are NumPy functions that return the index (or indices) of the smallest (for argmin) or largest (for argmax) element in an array. For example, if you have an array a = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5], numpy.argmin(a) would return 1, which is the index of the smallest element (1), and numpy.argmax(a) would return 5, which is the index of the largest element (9).



In [ ]:
np.argmin(b)

1

In [ ]:
np.argmax(b)

3

In [ ]:
np.argsort(b)

array([1, 0, 4, 2, 3], dtype=int64)

In [3]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# **Practice 7**
### Module basics:

**Math**

1) Basic exercise using the math module. Write a program that prompts the user to provide the radius of a circle and then calculates and prints the diameter, circumference, and area of the circle using the math module:

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
  
    import math...
    pi = math.pi
    diameter = 2.R
    circumference = 2.pi.R
    area = pi.R²

    print("Diameter:", diameter)
    print("Circumference:", circumference)
    print("Area:", area)
  
</details>

**Numpy**

3) Basic exercise using the NumPy module. Create a sequence of numbers using np.arange() then calculate the mean, standard deviation and maximum/minimum of this sequence.

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>

    # creates a sequence of numbers using numpy.arange()
    sequence = np.arange(....)

    # calculates the mean, standard deviation, and maximum of the sequence
    mean = np.mean...
    std_dev = np.std...
    max_val = np.max...
    # prints the results
    print("Mean:", mean)
    print("Standard deviation:", std_dev)
    print("Maximum value:", max_val)

  
</details>

4) Uses the np.where() function to find the indices of elements that are greater than the mean. Then assing for each index a value for values greater and less than the mean.

<details>
    <summary><font color=red> <p>&#128161;</p></font> </summary>
    
    indices = np.where(...)
    values = np.where(...)

  
</details>

#1)

#2)

#3)

#4)